// Writes src/audio/ALIGNMENT.md from alignment.json + the live manifest, so the report cannot drift from the render.
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { getSegments } from "../src/audio/manifest";
import { cuesFor } from "../src/audio/subtitles";
import alignment from "../src/audio/alignment.json";
import { FULL_SCENES, TEASER_SCENES, FPS, sceneStarts } from "../src/config/timing";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const t = (n: number) => n.toFixed(2);
const al = alignment as unknown as Record<string, { sourceDurationSec: number; cutsSec: number[]; pauses: number[][]; loudnormInput: Record<string, string> }>;
let md = `# Narration synchronization report

Generated by \`npm run audio:report\` from \`alignment.json\`. Sources are the four ElevenLabs recordings, kept unchanged in \`src/audio/source/\`
(note: the files are named \`.wav\` but contain MP3 data, 44.1 kHz mono, 128 kbps; they are decoded and mastered to 48 kHz mono PCM WAV).

## Method
1. \`ffmpeg silencedetect\` (${"-38 dB"}) finds every real pause. The pauses that separate the scripted segments are selected (indexes in \`scripts/align-narration.ts\`) and checked by a seconds-per-word sanity test.
2. Each cut is placed in the **middle of a pause**, so no word is cut or clipped; every file also gets a 20 ms fade at its edges (de-click).
3. The whole recording is loudness-normalised once (two-pass loudnorm, -16 LUFS integrated, -1.5 dBTP, then a limiter) and only then split, so levels are consistent across segments.
4. Each segment is placed on the timeline (\`NARRATION_START\` / \`TEASER_NARRATION_START\` in \`src/config/timing.ts\`) so its key phrases meet the matching visuals. Segments are never overlapped or shortened.
5. Subtitle cues are timed on the real speech: clause boundaries snap to the detected pauses (\`src/audio/subtitles.ts\`).
`;

for (const variant of ["full", "teaser"] as const) {
  for (const l of ["en", "fr"] as const) {
    const a = al[`${variant}-${l}`];
    md += `\n## ${variant === "full" ? "Full" : "Teaser"} ${l.toUpperCase()}\n\nSource ${a.sourceDurationSec} s. Input loudness ${a.loudnormInput.input_i} LUFS, true peak ${a.loudnormInput.input_tp} dBTP. Cuts in the source at ${a.cutsSec.join(", ")} s. Detected pauses: ${a.pauses.map((p) => `${p[0]}-${p[1]}`).join(", ")}.\n\n`;
    md += `| Segment (scene) | Starts on screen | Narration window | Duration | Scene/video ends | Slack |\n|---|---|---|---|---|---|\n`;
    const scenes = sceneStarts(variant === "full" ? FULL_SCENES : TEASER_SCENES);
    for (const s of getSegments(l, variant)) {
      const sc = scenes.find((x) => x.id === s.sceneId)!;
      const limit = variant === "full" ? (sc.from + sc.frames) / FPS : scenes[scenes.length - 1].from / FPS + scenes[scenes.length - 1].frames / FPS;
      md += `| ${s.sceneId} | ${t(sc.from / FPS)} s | ${t(s.startSec)}-${t(s.endSec)} s | ${t(s.durationSec)} s | ${t(limit)} s | ${t(limit - s.endSec)} s |\n`;
    }
    md += `\nSubtitle cues:\n\n| From | To | Text |\n|---|---|---|\n`;
    for (const s of getSegments(l, variant)) for (const c of cuesFor(s)) md += `| ${t(c.from / FPS)} | ${t(c.to / FPS)} | ${c.text} |\n`;
  }
}
md += `
## Fit and mismatches
* **Full videos:** every segment fits inside its scene with several seconds to spare (narration is 25.5 s EN / 28.8 s FR in a 60 s film), so no scene timing was changed.
* **Work orders and invoicing (both languages):** one continuous sentence ending in "payments / paiements". Started so that "work orders" meets the work-order screen and "branded invoices" meets the invoice, it says "payments" at about 36 s, over the invoice email (revealed ~36.5 s), roughly 3-4 s before the payment-record screen appears (~39.9 s). Smallest correction if you want an exact match: reveal the invoice email and the payment record about 2 s earlier (\`WorkOrders.tsx\`: email \`Pop start\` 238 -> ~180 and payment record 338 -> ~280 frames, shortening the invoice-PDF beat). Not applied, to keep the approved visuals; no words are affected either way.
* **Teaser:** the take is 8.5 s of speech in one run. The visual cut points of the approved teaser could not carry the closing phrase ("Meet GarageOS, the smarter way to manage your repair shop", about 3.9 s) inside a 3.0 s closing scene, so the teaser scene lengths were rebalanced by <= 0.9 s: hook 3.0 -> 2.5, booking 3.5 -> 2.9, inspection 3.0 -> 2.5, invoice 2.5 -> 3.2, closing 3.0 -> 3.9 (still 15.0 s). Animations and compositions are unchanged. "Appointments / Inspections / Invoices" now land on the booking, inspection and invoice scenes, and "Meet GarageOS" lands as the logo appears; the CTA stays on screen for the rest of the closing scene.
`;
writeFileSync(`${root}/src/audio/ALIGNMENT.md`, md);
console.log("wrote src/audio/ALIGNMENT.md");
